package ca.corbett.musicplayer.extensions.ai;

import ca.corbett.extensions.AppExtensionInfo;
import ca.corbett.extras.properties.AbstractProperty;
import ca.corbett.musicplayer.extensions.MusicPlayerExtension;
import ca.corbett.musicplayer.ui.VisualizationManager;

import java.util.ArrayList;
import java.util.List;

/**
 * This extension contributes custom visualizers that were generated by various
 * AI models as an experiment for YouTube. Very little human-generated code is in here,
 * other than the scaffolding to stand up the extension itself.
 */
public class AiVisualizerExtension extends MusicPlayerExtension {

    private final AppExtensionInfo extInfo;

    private final FloatingHexagons_Copilot floatingHexagonsVisualizer_Copilot;
    private final FloatingHexagons_Qwen36_35B_A3B floatingHexagonsQwen3635BA3B;
    private final FloatingHexagons_Qwen36_27B_dense floatingHexagonsQwen3627Bdense;

    public AiVisualizerExtension() {
        extInfo = AppExtensionInfo.fromExtensionJar(getClass(), "/extInfo.json");
        if (extInfo == null) {
            throw new RuntimeException("ExtensionTemplate: can't parse extInfo.json from jar resources!");
        }

        floatingHexagonsVisualizer_Copilot = new FloatingHexagons_Copilot();
        floatingHexagonsQwen3635BA3B = new FloatingHexagons_Qwen36_35B_A3B();
        floatingHexagonsQwen3627Bdense = new FloatingHexagons_Qwen36_27B_dense();
    }

    @Override
    public AppExtensionInfo getInfo() {
        return extInfo;
    }

    /**
     * Our visualizers can optionally expose configuration properties to the user,
     * if they have settings or options that can be adjusted.
     */
    @Override
    protected List<AbstractProperty> createConfigProperties() {
        List<AbstractProperty> list = new ArrayList<>();
        list.addAll(floatingHexagonsVisualizer_Copilot.getProperties());
        list.addAll(floatingHexagonsQwen3635BA3B.getProperties());
        list.addAll(floatingHexagonsQwen3627Bdense.getProperties());
        return list;
    }

    /**
     * If our visualizers need to load resources from our jar file, such as icons, images, or
     * sound effects, we must do that here. The class loader that loads our jar file will be
     * closed after this method is invoked, so we won't get another chance to load them later.
     */
    @Override
    protected void loadJarResources() {
    }

    /**
     * Invoked by the application either as the application is starting up, or when the
     * extension is enabled within the application. We can do extension-level initialization
     * here if we need to.
     */
    @Override
    public void onActivate() {
    }

    /**
     * Invoked either as the application is shutting down, or when the
     * extension is disabled within the application. We can do extension-level cleanup
     * here if we need to.
     */
    @Override
    public void onDeactivate() {
    }


    /**
     * The application will query us for our list of visualizers. We can return a list
     * with an instance of each of our visualizers here.
     */
    @Override
    public List<VisualizationManager.Visualizer> getCustomVisualizers() {
        return List.of(
            floatingHexagonsVisualizer_Copilot,
            floatingHexagonsQwen3635BA3B,
            floatingHexagonsQwen3627Bdense
        );
    }
}
